apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-org-service
  labels:
    app: spring-boot-org-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-org-service
  template:
    metadata:
      labels:
        app: spring-boot-org-service
    spec:
      containers:
      - name: organization
        image: subhakarkotta/spring-boot-org-service:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-org-service
  labels:
    app: spring-boot-org-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring-boot-org-service
